name: PrimeFaces
pygments: false

repo_url: http://primefaces.github.io/repository
browse_source: http://code.google.com/p/primefaces/source/browse
issue_tracker: http://code.google.com/p/primefaces/issues/detail?id=

analytics:
  track_id: UA-39073912-1

releases:
  unofficials:
  - version:   5.0.5
    revision:  11705
    date_time: 2014-08-06 08:24:40 -0000
    suffix:    "UR"

  - version:   5.0.4
    revision:  11633
    date_time: 2014-07-16 10:56:20 -0000
    suffix:    "UR"

  - version:   5.0.3
    revision:  11574
    date_time: 2014-06-30 12:25:56 -0000
    suffix:    "UR"

  - version:   5.0.2
    revision:  11511
    date_time: 2014-06-09 16:59:21 -0000
    suffix:    "UR"

  - version:   5.0.1
    revision:  11452
    date_time: 2014-05-26 17:20:14 -0000
    suffix:    "UR"

  - version:   4.0.6
    revision:  10498
    date_time: 2014-01-06 12:11:36 -0000
    suffix:    "UR2"

  - version:   3.5.22
    revision:  10498
    date_time: 2014-01-06 11:40:08 -0000
    suffix:    "UR2"

  - version:   4.0.5
    revision:  10349
    date_time: 2013-12-16 11:12:09 -0000
    suffix:    "UR"

  - version:   3.5.21
    revision:  10334
    date_time: 2013-12-16 10:32:37 -0000
    suffix:    "UR"

  - version:   4.0.4
    revision:  10263
    date_time: 2013-11-18 11:15:12 -0000
    suffix:    "UR"

  - version:   3.5.20
    revision:  10263
    date_time: 2013-11-18 11:04:21 -0000
    suffix:    "UR"

  - version:   4.0.3
    revision:  10235
    date_time: 2013-11-04 10:58:03 -0000
    suffix:    "UR"

  - version:   3.5.19
    revision:  10235
    date_time: 2013-11-04 10:41:20 -0000
    suffix:    "UR"

  - version:   4.0.2
    revision:  10202
    date_time: 2013-10-28 15:54:31 -0000
    suffix:    "UR"

  - version:   3.5.18
    revision:  10202
    date_time: 2013-10-28 15:49:10 -0000
    suffix:    "UR"

  - version:   4.0.1
    revision:  10158
    date_time: 2013-10-15 22:03:57 -0000
    suffix:    "UR"

  - version:   3.5.17
    revision:  10158
    date_time: 2013-10-15 21:02:11 -0000
    suffix:    "UR"

  - version:   3.5.16
    revision:  10105
    date_time: 2013-09-30 11:41:52 -0000
    suffix:    "UR"

  - version:   3.5.15
    revision:  10083
    date_time: 2013-09-25 10:45:33 -0000
    suffix:    "UR"

  - version:   3.5.14
    revision:  9944
    date_time: 2013-09-02 20:58:23 -0000
    suffix:    "UR"

  - version:   3.5.13
    revision:  9871
    date_time: 2013-08-21 13:22:53 -0000
    suffix:    "UR2"

  - version:   3.5.12
    revision:  9861
    date_time: 2013-08-19 13:21:17 -0000
    suffix:    "UR"

  - version:   3.5.11
    revision:  9742
    date_time: 2013-08-12 19:53:46 -0000
    suffix:    "UR"

  - version:   3.5.10
    revision:  9678
    date_time: 2013-07-29 15:39:59 -0000
    suffix:    "UR"

  - version:   3.5.9
    revision:  9636
    date_time: 2013-07-22 12:11:20 -0000
    suffix:    "UR"

  - version:   3.5.8
    revision:  9429
    date_time: 2013-07-01 12:23:10 -0000
    suffix:    "UR"

  - version:   3.5.7
    revision:  9352
    date_time: 2013-06-07 20:38:36 -0000
    suffix:    "UR"

  - version:   3.5.6
    revision:  9327
    date_time: 2013-06-03 07:05:16 -0000
    suffix:    "UR"

  - version:   3.5.5
    revision:  9306
    date_time: 2013-05-27 13:17:42 -0000
    suffix:    "UR"

  - version:   3.5.4
    revision:  9175
    date_time: 2013-05-13 10:07:49 -0000
    suffix:    "UR"

  - version:   3.5.3
    revision:  9003
    date_time: 2013-04-22 14:32:25 -0000
    suffix:    "UR"

  - version:   3.5.2
    revision:  8865
    date_time: 2013-03-31 13:54:19 -0000
    suffix:    "UR"

  - version:   3.5.1
    revision:  8807
    date_time: 2013-03-16 06:59:30 -0000
    suffix:    "UR"

  officials:
  - version: 3.5

